### ISSUE TITLE
How to make to run or-elm classification with iris database

### ISSUE THREAD

**Issue by alciomarhollanda** [chickenbestlover/Online-Recurrent-Extreme-Learning-Machine#2]
Hello, i would like to learn, how to make to run or-elm classification with iris database.

Is it  possible ?

**Comment by chickenbestlover** [comment]
Hello,
This repo is suited for Time-series regression, where data is in form of a sequence.
If I'm correct, iris database is for image classification.
If you want to use ELMs on iris dataset, you might want to check [this repo](https://github.com/chickenbestlover/ELM-pytorch).
